### PR TITLE
 feat: support go-redis/v9

### PR DESCRIPTION
**Pull request by jkskj**
Add support for new go-redis version v9.
The Hook interface has changed significantly in v9.

``` go
// old v8
type Hook interface {
	BeforeProcess(ctx context.Context, cmd Cmder) (context.Context, error)
	AfterProcess(ctx context.Context, cmd Cmder) error

	BeforeProcessPipeline(ctx context.Context, cmds []Cmder) (context.Context, error)
	AfterProcessPipeline(ctx context.Context, cmds []Cmder) error
}
```

``` go
// new v9
type Hook interface {
	DialHook(next DialHook) DialHook  
	ProcessHook(next ProcessHook) ProcessHook  
	ProcessPipelineHook(next ProcessPipelineHook) ProcessPipelineHook  
}

type (
	DialHook            func(ctx context.Context, network, addr string) (net.Conn, error)
	ProcessHook         func(ctx context.Context, cmd Cmder) error
	ProcessPipelineHook func(ctx context.Context, cmds []Cmder) error
)
```

### CODE REVIEW

**Comment by GuangmingLuo** [comment]
Hi, are you a user of this repo ? Actually, we want to archive this repo. Users are suggested to use OpenTelemetry.

**Comment by jkskj** [comment]
Yes,I'm a user of this repo.In this case,should I close this pr?

**Comment by GuangmingLuo** [comment]
OpenTracing is officially archived by CNCF, please use OpenTelemetry instead.

**Comment by jkskj** [comment]
Thank you,I will close this pr.

**Pull request closed without merging**
